### ISSUE TITLE
activate, play 2.2 호환성 문제 해결

### ISSUE THREAD

**Issue by tantara** [wafflestudio/wall#106]
play 2.2로 업데이트 한 이후에

모든 db 트랜잭션이 먹통됨

**Comment by tantara** [comment]
[JdbcSQLException: Hexadecimal string contains non-hex character: "tantara.tm@gmail.com"; SQL statement: SELECT s1.id FROM "USER" s1 WHERE (s1."EMAIL" = ? and s1."PROVIDER" = ?) [90004-172]]

이런 에러를 뿜음

**Comment by tantara** [comment]
h2, play 호환성 문제
http://stackoverflow.com/questions/14197779/uploading-a-file-in-java-play-1-2-3-then-storing-file-as-byte-array-causes-persi

http://grokbase.com/t/gg/play-framework/133hc01keg/2-1-cannot-insert-a-blob

**Comment by tantara** [comment]
일단 디비를 지우고 새로 만들면 문제가 없네요.
위의 링크처럼 이전 버전에 만들어진 h2 테이블의 칼럼 타입의 문제가 있는듯...

좀 더 알아보겠슴다

**Comment by kindone** [comment]
transactional {} 블럭 넣어서 해결된 듯?

**Comment by kindone** [comment]
dev에서 해보니까 아직 문제가 있는듯...

**Comment by kindone** [comment]
애초에 테이블이 만들어질때 email의 타입이 varchar가 아니라 varbinary로 만들어지는게 문제인것 같은데 왜 그런지 알아봐야

**Comment by kindone** [comment]
결국 그냥 varchar 만들도록 강제해버림 ㅋ

**Comment by kindone** [comment]
activate를 1.4.4로 업그레이드
