### ISSUE TITLE
Add retry on connection lost

### ISSUE THREAD

**Issue by kindone** [wafflestudio/wall#31]

**Comment by serendipitydeity** [comment]
연결이 끊어졌을 때 화면에 끊어졌다고 표시해주기

**Comment by kindone** [comment]
1. define persistent websocket class (done)
2. apply reconnection to chat (done)
3. apply reconnection to wall 
4. show connection status

**Comment by kindone** [comment]
1. apply reconnection to wall (done)

**Comment by kindone** [comment]
대충 연결 상태는 채팅 윈도우 opacity로 확인가능 ㅋ
