### ISSUE TITLE
Movable.coffee에서 getter/setter pattern 바꿈

### ISSUE THREAD

**Issue by serendipitydeity** [wafflestudio/wall#53]
overriding 하기 위해서 return unless ~ 이건 existence 를 확인하기 때문에 느린듯

getter / setter를 defineProperty? 이거 써서 만들면 훨씬 빨라질듯

**Comment by yyhpys** [comment]
요 부분에서 indent 에러가 마구 터지는데 혹시 다른 디펜던시가 있는지?

error in: coffee -p /home/yyhpys/workspace/wall/infinitewall/app/assets/javascripts/movable.coffee /home/yyhpys/workspace/wall/infinitewall/app/assets/javascripts/movable.coffee:17:1: error: unexpected INDENT get: -> parseInt(@element.css('x')) ^^^^

**Comment by serendipitydeity** [comment]
오 형 웰컴백.. 오랜만이에요

클론 받아도 그렇게 되나요? 저랑 원욱이형은 잘 되는것같은데..

**Comment by yyhpys** [comment]
새로 클론받은 버전입니다 ㅇㅇ 다음서버에서 작업중이고..
coffeescript 1.6.2 (dependent on node 0.10.2)에서 발생
comma를 사용하면 해결되긴 하는데 근본적인 해결인지 확실하지가 않음..

**Comment by serendipitydeity** [comment]
다음서버에서 함 해보겠음당

**Comment by serendipitydeity** [comment]
흠 일단 apt-get 으로 coffeescript 1.2.0 받았는데 됩니다 

1.6.2에선 어떨지 모르겠네요

아마 그새 vim 설정이 바뀐게 아닐까요 ㄷㄷ 제 vimrc는 제 리포지토리 중 vimsettings에 있음요

**Comment by yyhpys** [comment]
v1.2.0으로 쓰니 잘 되는군여.. 버전업하면서 정책이 바뀐게 아닐까 싶군요
