### ISSUE TITLE
시트를 이동시키면 다른 쪽에서 간혹 다른 시트를 이동시킴

### ISSUE THREAD

**Issue by kindone** [wafflestudio/wall#57]
정확한 조건은 잘 모르겠는데 시트 관리를 id로 제대로 하지 않아서가 아닌지?

**Comment by serendipitydeity** [comment]
시트는 stage.sheets 에 id를 키로 갖는 오브젝트로 있는데 ㄷㄷ
이런경우 못봤는데 어떤 경우에 그런지 알고싶네요

**Comment by kindone** [comment]
오호라.. 내가 이 엄청난 기능을 몰라보고.. 포커스되어 있는 시트는 정지시켜놔서 대신 다른 시트가 움직이는 것 처럼 해놨구나...
