### ISSUE TITLE
Grid enhancement

### ISSUE THREAD

**Issue by serendipitydeity** [wafflestudio/wall#60]
Grid-based movement를 개선하기 위해서 시트를 움직일 때 시트의 파란색 테두리만 마우스를 따라가게 한 후, 월 바닥에는 이에 해당하는 grid cell을 표시해준다. 마우스를 놓으면 해당 cell에 애니메이션으로 시트가 미끄러져 들어감

**Comment by kindone** [comment]
우와아앙..
