### ISSUE TITLE
History 기능을 위한 Text Operation undo 기능 구비

### ISSUE THREAD

**Issue by kindone** [wafflestudio/wall#62]
- operation에 대한 undo  operation 생성 
  - insert -> delete, delete ->insert ... 현재 state + operation => undo operation
- operation+undo operation 리스트에 저장 
- undo: 현 state에 대해 undo operation적용.. mine이 나올때까지
- redo: undo의 반대

**Comment by kindone** [comment]
흐으 일단 다큐멘테이션을 만들어야겠다 헷갈림...

**Comment by tantara** [comment]
오호 insert <-> delete로 생각하니깐 명확해지네요
