### ISSUE TITLE
파일 업로드 개선

### ISSUE THREAD

**Issue by serendipitydeity** [wafflestudio/wall#64]
파일 업로드시 파일 이름이 그대로 들어가는데, 한글 파일이나 공백이 들어간 경우 뭔가 서버에 커밋이 들어갈때마다 꼬이는 등 잘 안됨. 저장할때는 임의의 아스키 스트링으로 저장해야할듯

**Comment by tantara** [comment]
서버 - 리눅스
클라 - 윈도우 IE11, 윈도우 크롬

에서 정상 작동
