### ISSUE TITLE
File type detection

### ISSUE THREAD

**Issue by serendipitydeity** [wafflestudio/wall#69]
지금은 그냥 무작정 들어가는데 타입을 감지해서 적절한 대응을 하는게 좋을듯

Apache Tika 사용?

**Comment by tantara** [comment]
apache tika는 이용하지 않았고
http form에서 얻어지는 값으로 판단

**Comment by serendipitydeity** [comment]
흠 거기서 얻어오면 좀 위험할텐데 

저걸 어디서 쓰려고 했냐면 파일이 업로드 되면 이게 만약 이미지라면 이미지 시트로 만들고 아니라면 적절한 처리를 해 줄라고 했었는데 만약 엉뚱한 값이 들어와버리면 큰일날듯

**Comment by tantara** [comment]
그럼 tika를 써야겠군 ㄱㄱㄱㄱ

2013년 8월 28일 오후 2:09, Jae Ho Jeon notifications@github.com님의 말:

**Comment by tantara** [comment]
tika를 쓰면 image/jpeg가 application/octet-stream를 리턴한다...

좀 더 알아봐야겠군

2013년 8월 28일 오후 2:27, Taekmin Kim tantara.tm@gmail.com님의 말:
