### ISSUE TITLE
이미지를 실제보다 축소된 썸네일로 보여줌

### ISSUE THREAD

**Issue by kindone** [wafflestudio/wall#70]
모든 이미지를 실제 크기로 보여줄 경우 성능이슈나 메모리 이슈가 있을 수 있다.

이미지가 큰 경우 실제보다 축소된 썸네일로 보여주고 (예를 들어) 클릭했을 경우 모달로 풀 이미지를 보여줌.

**Comment by tantara** [comment]
jdk 1.7 필요

thumbnail routing 아래 링크 참고
https://github.com/wafflestudio/wall/blob/5ebd86a782641ccfb41c86be2f93a96234d26910/infinitewall/conf/routes#L71

예제:
http://walnut.wafflestudio.net:9000/thumb/100/100/DSC_0001.JPG

**Comment by tantara** [comment]
한글로 된 파일은 썸네일 경로에서 못찾음
