### ISSUE TITLE
group wall 생성이 안되는듯

### ISSUE THREAD

**Issue by serendipitydeity** [wafflestudio/wall#74]
group 에서 wall을 추가하거나 생성이 안됨

**Comment by serendipitydeity** [comment]
'group' 이라는 것이 sql 예약어인듯
Activate로 바꾸면서 자동으로 테이블 생성하면서 충돌 일어나는듯

**Comment by kindone** [comment]
@Alias("PersonTable")
class Person(@Alias("personName") var name: String) extends Entity

이런식으로 Group에 대한 table이름을 다른 것으로 만들어야 할듯 UserGroup이나 그런걸로

http://activate-framework.org/documentation/entity/
