### ISSUE TITLE
jquery 2.0.2 min.js에서 이상한 경로에 있는 js 파일 링크

### ISSUE THREAD

**Issue by tantara** [wafflestudio/wall#95]
이미지 시트를 만들 경우(즉, 이미지 업로드 할때)에 

not found jquery.min.map이라는 에러가 나는데

https://github.com/wafflestudio/wall/commit/80de4e869c01c884b50cea4cda6eec2d934b6fcb

여기 문제인듯함. 우선 @를 지워서 해결했는데 플레이랑 충돌나는건지 확인을 못함

**Comment by serendipitydeity** [comment]
이거 크롬 업데이트 된 이후로 제이쿼리 쓰는 많은 사이트들에서 나타나는 문제인데 원인을 잘 모르겠음 아마 크롬이 업데이트 되면 조만간 해결되지 않을까싶음

**Comment by tantara** [comment]
아아 그렇군
골뱅이@ 괜히 지웠네

2013년 8월 28일 오후 2:30, Jae Ho Jeon notifications@github.com님의 말:

**Comment by kindone** [comment]
크롬에 source map 이라는 기능이 들어갔음.

커피스크립트에서도 generate할 수 있는데 컴파일된 js에서 실행하다가 문제가 있을때 원래 소스(coffee)상에 어느 위치인지
표시해주는? 그런 기능인듯

2013/8/28 Taekmin Kim notifications@github.com

**Comment by tantara** [comment]
크롬의 경우에 개발자도구를 열고 우측 하단에 있는 톱니바퀴를 누르고 enable source map을 해제하면 문제 해결되는듯합니다
